image: docker:latest

services:
  - docker:dind

stages:
  - test
  - package

api-test:
  stage: test
  script:
    - docker build -t registry.gitlab.com/leokraken/opensubtitlesbot/api:latest api
    - docker run --rm registry.gitlab.com/leokraken/opensubtitlesbot/api:latest npm test

api-package:
  stage: package
  only:
    - master
  script:
    - docker build -t registry.gitlab.com/leokraken/opensubtitlesbot/api:latest api
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/leokraken/opensubtitlesbot/api
