version: '2'
services:
  database:
    image: mongo
    volumes:
      - "mongodbdata:/data"
  api:
    environment:
       - MONGO_HOST=database
       - MONGO_PORT=27017
       - MONGO_DB=imdb
    build:
      context: './api'
    ports:
      - "8080:8080"

