version: '2'
services:
  database:
    image: postgres
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
  api:
    restart: always
    environment:
       - DB_HOST=database
       - DB_PORT=5432
       - DB_NAME=postgres
       - DB_USER=postgres
    build:
      context: './api'
    ports:
      - "8080:8080"

volumes:
   postgresdata: